import type { Metadata } from "next";
import { dunbarText } from "@/public/fonts/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dunbarText.variable} antialiased`}>{children}</body>
    </html>
  );
}
